export { default as Banner } from './Banner'
export { default as NewProduct } from './NewProduct'
export { default as OutstandingProducts } from './OutstandingProducts'
export { default as GalleryProducts } from './GalleryProducts'
export { default as Slide } from './Slide'
